spring.application.name=producerkafka
server.port=0

spring.kafka.producer.bootstrap-servers=localhost:9092,localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
app.kafka.product-created-topic= product-created-events-topic

#High reliability settings
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.properties.enable.idempotence=true

# increase throughput by buffering small messages
spring.kafka.producer.properties.linger.ms=20


# Access UI at: http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs